nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ['https://openmagmedia.flutterflow.app'] # Ajoutez ici le domaine de votre application FlutterFlow
    allow_headers: ['Content-Type', 'Authorization' , 'Origin' , 'Referer' , 'Host']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
    expose_headers: []
    max_age: 3600
