version: '3'

services:
###> doctrine/doctrine-bundle ###
  # database:
  #   ports:
  #     - "5432"
###< doctrine/doctrine-bundle ###

  redis:
    image: redis:latest

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###