version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      # You should definitely change the password in production
      MYSQL_DATABASE: 'adlist' # utiliser cette commande pour test
    ports:
      - '3306:3306'
    volumes:
      - ./var/db/mysql:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
